### ISSUE TITLE
Jetpack scoreboard is shown but no game is available

### ISSUE THREAD

**Issue by digitaltoast** [google/santa-tracker-android#10]
Version 4.0.12, Android 6.0. the scoreboard for Jetpack is still working and strangely showing scores today, even though it looks like jetpack game has been removed from the app.

**Comment by samtstern** [comment]
@digitaltoast thanks for the bug report!  That's a good catch, we moved the Jetpack game in the app (it's now a mini game within Present Quest) but didn't make the appropriate changes to Play Games.
