### ISSUE TITLE
Can I publish this App with a renamed package on Google PlayStore ?

### ISSUE THREAD

**Issue by steve111MV** [google/santa-tracker-android#11]
I would like to modify this app a bit and publish under a new package name (id) on PlayStore. Does the liscence allow me to do so ?

**Comment by samtstern** [comment]
@steve111MV the code in this repository is licensed under Apache 2.0.  You'll have to read an understand the `LICENSE`.  It would be inappropriate for me to give you any further advice than that as I am not a lawyer.

**Comment by AndroidDeveloperLB** [comment]
So I think it's ok, as all is very permissive on Apache2 , no?
But it includes code. What about the content (images, sounds, etc... ) ?
