### ISSUE TITLE
Chromecast is broken from Android

### ISSUE THREAD

**Issue by joekiller** [google/santa-tracker-android#14]
At least on my Nexus 6

**Comment by ankurkotwal** [comment]
Can you be more specific about how its broken? Chromecast is not enabled for 2017 so it shouldn't be available at all.

**Comment by joekiller** [comment]
The help page implies that it works from the app. Thanks for the information.Here is the link that says it will work from the app: https://support.google.com/santatracker/answer/4243795?visit_id=1-636497548954590286-3031909940&rd=1

**Comment by ankurkotwal** [comment]
Thanks for pointing that out. We need to update this page. I'm sorry Chromecast was not available this year but I hope you enjoy Santa Tracker on Android.

**Comment by joekiller** [comment]
We are Chromecasting via the browser. Thank you for your efforts!!!!

**Comment by ankurkotwal** [comment]
👍 Happy holidays!
🎅🏼🎄🎁
