### ISSUE TITLE
Are the locations pre-programmed into the source code, or is the fake location of Santa Claus processed server-side?

### ISSUE THREAD

**Issue by fffelix-jan** [google/santa-tracker-android#39]
This is not an issue. I'm just asking a question.

**Comment by samthor** [comment]
Santa publishes his route at a HTTP location that we fetch via Firebase Remote Config. It's not in any verison's source code.

If he diverges from this route, we get an update immediately via Remote Config and fetch the new route.

**Comment by fffelix-jan** [comment]
Is the route already online?

**Comment by deopdeop** [comment]
https://firebasestorage.googleapis.com/v0/b/santa-tracker-firebase.appspot.com/o/route%2Fsanta_en.json?alt=media

**Comment by fffelix-jan** [comment]
Wow, thanks for showing me!
