### ISSUE TITLE
offline-lib-repository folder lack of jars such as sugar-1.4.jar easypermissions.jar etc

### ISSUE THREAD

**Issue by asalin** [google/santa-tracker-android#5]
when i import the project into android studio,it always pop up the same message,couldn't find jar on specific folder inside offline-lib-repository

**Comment by swigidysworo** [comment]
I am also having the same problem, can't find sugar.jar, etc.

**Comment by samtstern** [comment]
@asalin @swigidysworo can you post the exact error message here?

**Comment by asalin** [comment]
@samtstern 
Error:Could not find leakcanary-android.jar (com.squareup.leakcanary:leakcanary-android:1.5).
Searched in the following locations:
    file:/D:/workspace_studio/santa-tracker-android-master/third_party/offline-lib-repository/com/squareup/leakcanary/leakcanary-android/1.5/leakcanary-android-1.5.jar

**Comment by swigidysworo** [comment]
@samtstern 
Error:Could not find sugar.jar (com.github.satyan:sugar:1.4).
Searched in the following locations:
    file:/E:/AndroidStudioProjects/santa-tracker-android-master/third_party/offline-lib-repository/com/github/satyan/sugar/1.4/sugar-1.4.jar

**Comment by ajaykumarmeher** [comment]
Gradle 'santa-tracker-android-latest' project refresh failed
Error:Could not find constraint-layout.jar (com.android.support.constraint:constraint-layout:1.0.0-beta2).
Searched in the following locations:
    file:/Users/ajay.meher/StudioProjects/santa-tracker-android-latest/third_party/offline-lib-repository/com/android/support/constraint/constraint-layout/1.0.0-beta2/constraint-layout-1.0.0-beta2.jar

**Comment by samtstern** [comment]
@ajaykumarmeher  @asalin  @swigidysworo are you all on Windows machines?  This could be a Windows compatibility issue with how we structure our build scripts.

**Comment by swigidysworo** [comment]
@samtstern
I am using a mac currently, but I do have a windows machine. I will try using windows and report back when tested.

**Comment by ajaykumarmeher** [comment]
@samtstern yes I am currently using the windows machine. But, I have checked the repo and indeed the jar file is missing. Please have a look.
![constraint_layout_jar_missing_in_the_repo](https://cloud.githubusercontent.com/assets/839596/25143288/7a9299ba-2487-11e7-972f-14b4b0b9e8bb.PNG)

**Comment by swigidysworo** [comment]
@ajaykumarmeher @samtstern That is true, there are multiple jar files missing in the repo.

**Comment by samtstern** [comment]
Ah I figured out what this is!  I'll get a fix in shortly.

**Comment by samtstern** [comment]
I submitted PR #6 which should fix this issue.  Let me know if that does not work!
